GET http://localhost:3000/subscribers

###
GET http://localhost:3000/subscribers/61bc08fe219a3577f56829d3


###
PATCH  http://localhost:3000/subscribers/61bc08f3219a3577f56829d1
Content-Type: application/json


{
    "name": "Teddy Omondi"
}


###
DELETE  http://localhost:3000/subscribers/61bc08fe219a3577f56829d3
